import { CardBase, CardRarity } from '../../../types/cards';

export const CAN_CUP_CATEGORIES = [
  'Ölmärken',
  'Skidorter',
  'Länder i Europa',
  'Fotbollslag',
  'Filmer med Leonardo DiCaprio',
  'Djur',
  'Städer i Sverige',
  'Reality-serier',
  'Drinkar',
  'Artister som spelat på Way Out West',
  'Bilmärken',
  'Svenska Youtubers',
  'Sportgrenar',
  'Maträtter från Asien',
  'Netflix-serier',
  'Saker man hittar i en bar',
];

export const CAN_CUP_TONGUE_TWISTERS = [
  'Sex laxar i en laxask.',
  'Sju sjösjuka sjömän sköttes av sju sköna sjuksköterskor.',
  'Flyg fula fluga, flyg! Och den fula flugan flög.',
  'Packa pappas kappsäck.',
  'Kvist friskt, raska kvastar.',
  'Knut satt vid en knut och knöt en knut, när Knut hade knutit knuten var knuten knuten.',
  'Droskkusken Max kuskar med raska droskhästar.',
  'En barfotad arab badar i en bäck.',
  'Sex snabba snigel-snappande snokar snodde snopet snoken snabbt.',
  'Sjuttiosju sköna sjuksköterskor sköter sju sjösjuka sjömän på skeppet Shanghai.',
];

export const CAN_CUP_CARDS: CardBase[] = [
  {
    id: 'cc-take-a-sip',
    name: 'Ta en Klunk',
    description: 'Ge 1 klunk.',
    manaCost: 0,
    sipCost: 0,
    rarity: CardRarity.COMMON,
    type: 'targeted',
    effect: { type: 'canCupSip', value: 1 },
    requiresTarget: true,
    color: 'cyan',
  },
  {
    id: 'cc-social',
    name: 'Skål!',
    description: 'Alla andra tar 2 klunkar.',
    manaCost: 0,
    sipCost: 0,
    rarity: CardRarity.COMMON,
    type: 'aoe',
    effect: { type: 'canCupAoESip', value: 2 },
    requiresTarget: false,
    color: 'cyan',
  },
  {
    id: 'cc-water-break',
    name: 'Vattenpaus',
    description: '+2 vattensklunkar.',
    manaCost: 0,
    sipCost: 0,
    rarity: CardRarity.COMMON,
    type: 'normal',
    effect: { type: 'canCupWater', value: 2 },
    requiresTarget: false,
    color: 'teal',
  },
  {
    id: 'cc-sip-deflection',
    name: 'Nödvatten',
    description: '+1 vattensklunk.',
    manaCost: 0,
    sipCost: 0,
    rarity: CardRarity.COMMON,
    type: 'normal',
    effect: { type: 'canCupWater', value: 1 },
    requiresTarget: false,
    color: 'teal',
  },
  {
    id: 'cc-top-up',
    name: 'Fyll på',
    description: '+2 klunkar i din burk.',
    manaCost: 0,
    sipCost: 0,
    rarity: CardRarity.COMMON,
    type: 'normal',
    effect: { type: 'canCupTopUp', value: 2 },
    requiresTarget: false,
    color: 'blue',
  },
  {
    id: 'cc-pass-it-on',
    name: 'Passa Vidare',
    description: 'Ge 2 klunkar. Målet ger sedan vidare 2 klunkar.',
    manaCost: 0,
    sipCost: 0,
    rarity: CardRarity.COMMON,
    type: 'targeted',
    effect: { type: 'canCupRelaySip', value: 2 },
    requiresTarget: true,
    color: 'cyan',
  },

  {
    id: 'cc-double-trouble',
    name: 'Dubbel Trouble',
    description: 'Ge 4 klunkar.',
    manaCost: 1,
    sipCost: 1,
    rarity: CardRarity.RARE,
    type: 'targeted',
    effect: { type: 'canCupDoubleTrouble', value: 4 },
    requiresTarget: true,
    color: 'indigo',
  },
  {
    id: 'cc-can-swap',
    name: 'Burkbyte',
    description: 'Byt burk med valfri spelare.',
    manaCost: 1,
    sipCost: 1,
    rarity: CardRarity.RARE,
    type: 'targeted',
    effect: { type: 'canCupSwap', value: 0 },
    requiresTarget: true,
    color: 'violet',
  },
  {
    id: 'cc-pressure-wave',
    name: 'Tryckvåg',
    description: 'Ge 2 klunkar. Målet ger sedan vidare 2 klunkar.',
    manaCost: 0,
    sipCost: 0,
    rarity: CardRarity.RARE,
    type: 'targeted',
    effect: { type: 'canCupRelaySip', value: 2 },
    requiresTarget: true,
    color: 'violet',
  },
  {
    id: 'cc-vampiric-chug',
    name: 'Gimmi Gimmi',
    description: 'Stjäl 2 klunkar från valfri spelare.',
    manaCost: 0,
    sipCost: 0,
    rarity: CardRarity.RARE,
    type: 'targeted',
    effect: { type: 'canCupVampire', value: 2 },
    requiresTarget: true,
    color: 'emerald',
  },
  {
    id: 'cc-bathroom-break',
    name: 'Toapaus',
    description: 'Immunitet till din nästa tur.',
    manaCost: 1,
    sipCost: 1,
    rarity: CardRarity.RARE,
    type: 'normal',
    effect: { type: 'canCupBathroomBreak', value: 0 },
    requiresTarget: false,
    color: 'teal',
  },
  {
    id: 'cc-spill',
    name: 'Vaska För I Helvete!',
    description: 'Förstör målets vatten. Ge 1 klunk.',
    manaCost: 1,
    sipCost: 1,
    rarity: CardRarity.RARE,
    type: 'targeted',
    effect: { type: 'canCupRemoveDefense', value: 1 },
    requiresTarget: true,
    color: 'red',
  },
  {
    id: 'cc-evaporation',
    name: 'Ökentorka',
    description: 'Förstör alla andras vatten.',
    manaCost: 2,
    sipCost: 2,
    rarity: CardRarity.RARE,
    type: 'aoe',
    effect: { type: 'canCupRemoveDefense', value: 0 },
    requiresTarget: false,
    color: 'orange',
  },
  {
    id: 'cc-holy-alliance',
    name: 'Helig Allians',
    description: 'Du och målet får +1 vattensklunk. Alla andra tar 2 klunkar.',
    manaCost: 0,
    sipCost: 0,
    rarity: CardRarity.RARE,
    type: 'targeted',
    effect: { type: 'canCupHolyAlliance', value: 1 },
    requiresTarget: true,
    color: 'teal',
  },
  {
    id: 'cc-vapenvila',
    name: 'Vapenvila',
    description: 'Du och målet får +2 vattensklunkar.',
    manaCost: 0,
    sipCost: 0,
    rarity: CardRarity.RARE,
    type: 'targeted',
    effect: { type: 'canCupHolyAlliance', value: 2 },
    requiresTarget: true,
    color: 'teal',
  },
  {
    id: 'cc-rock-bottom',
    name: 'Botten Är Nådd',
    description: 'Ge 1 klunk + 2 extra per tom burk du har.',
    manaCost: 0,
    sipCost: 0,
    rarity: CardRarity.RARE,
    type: 'targeted',
    effect: { type: 'canCupRockBottom', value: 1 },
    requiresTarget: true,
    color: 'emerald',
  },
  {
    id: 'cc-penalty-drink',
    name: 'Straffskål',
    description: 'Alla tar 1 klunk per tom burk de har.',
    manaCost: 0,
    sipCost: 0,
    rarity: CardRarity.RARE,
    type: 'aoe',
    effect: { type: 'canCupPenaltyDrink', value: 0 },
    requiresTarget: false,
    color: 'rose',
  },

  {
    id: 'cc-arm-wrestle',
    name: 'Armbrytning',
    description: 'Utmana någon. Förloraren tar 5 klunkar.',
    manaCost: 2,
    sipCost: 2,
    rarity: CardRarity.EPIC,
    type: 'challenge',
    effect: {
      type: 'challenge',
      value: 0,
      winnerEffect: { type: 'null', value: 0 },
      loserEffect: { type: 'canCupSip', value: 5 },
    },
    requiresTarget: true,
    isChallenge: true,
    challengeParticipantMode: 'owner-target',
    color: 'purple',
  },
  {
    id: 'cc-category-random',
    name: 'Kategori',
    description: 'Turtagning: Säg något i kategorin. Förloraren tar 3 klunkar.',
    manaCost: 2,
    sipCost: 2,
    rarity: CardRarity.EPIC,
    type: 'challenge',
    effect: {
      type: 'challenge',
      value: 0,
      winnerEffect: { type: 'null', value: 0 },
      loserEffect: { type: 'canCupSip', value: 3 },
    },
    requiresTarget: true,
    isChallenge: true,
    color: 'purple',
  },
  {
    id: 'cc-the-chug',
    name: 'Svep!',
    description: 'Målet sveper resten av sin burk!',
    manaCost: 2,
    sipCost: 2,
    rarity: CardRarity.EPIC,
    type: 'targeted',
    effect: { type: 'canCupBottenUpp', value: 0 },
    requiresTarget: true,
    color: 'rose',
  },
  {
    id: 'cc-legendary-heist',
    name: 'Legendary Heist',
    description: 'Stjäl en legendary från slumpvald spelare. Om de saknar en, tar DU 6 klunkar.',
    manaCost: 1,
    sipCost: 1,
    rarity: CardRarity.EPIC,
    type: 'auto-targeted',
    effect: { type: 'canCupLegendaryHeist', value: 6 },
    requiresTarget: false,
    color: 'amber',
  },
  {
    id: 'cc-tax-the-sober',
    name: 'Nykterist-Jakten',
    description: 'Spelaren med minst tomma burkar tar 5 klunkar.',
    manaCost: 1,
    sipCost: 1,
    rarity: CardRarity.EPIC,
    type: 'auto-targeted',
    effect: { type: 'canCupTaxSober', value: 5 },
    requiresTarget: false,
    color: 'fuchsia',
  },
  {
    id: 'cc-flamingo',
    name: 'Flamingon',
    description: 'Alla står på ett ben. Första som trillar tar 5 klunkar.',
    manaCost: 2,
    sipCost: 2,
    rarity: CardRarity.EPIC,
    type: 'challenge',
    effect: {
      type: 'challenge',
      value: 0,
      winnerEffect: { type: 'null', value: 0 },
      loserEffect: { type: 'canCupSip', value: 5 },
    },
    requiresTarget: false,
    isChallenge: true,
    color: 'purple',
  },
  {
    id: 'cc-clash-royale-mega-draft',
    name: 'Clash Royale Mega Draft',
    description: 'Välj två spelare som möts i Clash Royale. Förloraren tar 6 klunkar.',
    manaCost: 2,
    sipCost: 2,
    rarity: CardRarity.EPIC,
    type: 'challenge',
    effect: {
      type: 'challenge',
      value: 0,
      winnerEffect: { type: 'null', value: 0 },
      loserEffect: { type: 'canCupSip', value: 6 },
    },
    requiresTarget: true,
    isChallenge: true,
    color: 'purple',
  },
  {
    id: 'cc-tongue-twister',
    name: 'Tungvrickaren',
    description: 'Målet måste läsa en tungvrickare felfritt eller ta 3 klunkar.',
    manaCost: 1,
    sipCost: 1,
    rarity: CardRarity.EPIC,
    type: 'challenge',
    effect: {
      type: 'challenge',
      value: 0,
      winnerEffect: { type: 'null', value: 0 },
      loserEffect: { type: 'canCupSip', value: 3 },
    },
    requiresTarget: true,
    isChallenge: true,
    challengeParticipantMode: 'owner-target',
    challengeOutcomeRule: 'owner-safe',
    color: 'purple',
  },
  {
    id: 'cc-rock-paper-scissors',
    name: 'Sten, Sax, Påse',
    description: 'Utmana någon i Sten, Sax, Påse (Bäst av 3). Vinner du tar målet 4 klunkar.',
    manaCost: 1,
    sipCost: 1,
    rarity: CardRarity.EPIC,
    type: 'challenge',
    effect: {
      type: 'challenge',
      value: 0,
      winnerEffect: { type: 'null', value: 0 },
      loserEffect: { type: 'canCupSip', value: 4 },
    },
    requiresTarget: true,
    isChallenge: true,
    challengeParticipantMode: 'owner-target',
    challengeOutcomeRule: 'owner-safe',
    color: 'purple',
  },
  {
    id: 'cc-russian-roulette',
    name: 'Rysk Roulette',
    description: 'En slumpmässig spelare sveper hela sin burk.',
    manaCost: 2,
    sipCost: 2,
    rarity: CardRarity.EPIC,
    type: 'auto-targeted',
    effect: { type: 'canCupRussianRoulette', value: 0 },
    requiresTarget: false,
    color: 'red',
  },

  {
    id: 'cc-hur-full-e-du',
    name: 'HUR FULL E DU?',
    description: 'Reaktionstest! Förloraren sveper 2 hela burkar.',
    manaCost: 2,
    sipCost: 2,
    rarity: CardRarity.LEGENDARY,
    type: 'challenge',
    effect: {
      type: 'challenge',
      value: 0,
      winnerEffect: { type: 'null', value: 0 },
      loserEffect: { type: 'canCupSip', value: 20 },
    },
    requiresTarget: true,
    isChallenge: true,
    isLegendary: true,
    challengeParticipantMode: 'owner-target',
    color: 'amber',
    flavorText: 'Guld är guld. Snabbast hand överlever.',
  },
  {
    id: 'cc-bottom-race-random',
    name: 'BOTTENRACE',
    description: 'Svep-race mot slumpad spelare! Vinnaren får +10 vattensklunkar.',
    manaCost: 2,
    sipCost: 2,
    rarity: CardRarity.LEGENDARY,
    type: 'challenge',
    effect: {
      type: 'challenge',
      value: 0,
      winnerEffect: { type: 'canCupWater', value: 10 },
      loserEffect: { type: 'null', value: 0 },
    },
    requiresTarget: false,
    isChallenge: true,
    isLegendary: true,
    color: 'amber',
    flavorText: 'Hoppas din burk inte redan är tom...',
  },
  {
    id: 'cc-give-empty-can',
    name: 'PANTA MIN BURK!',
    description: 'Ge en av dina tomma burkar till valfri spelare.',
    manaCost: 2,
    sipCost: 2,
    rarity: CardRarity.LEGENDARY,
    type: 'targeted',
    effect: { type: 'canCupGiveEmptyCan', value: 1 },
    requiresTarget: true,
    isLegendary: true,
    color: 'amber',
    flavorText: 'Pantamera!',
  },
];
