import { CardBase, CardRarity } from '../../../types/cards';

export const CAN_CUP_CATEGORIES = [
  'Ölmärken',
  'Skidorter',
  'Länder i Europa',
  'Fotbollslag',
  'Filmer med Leonardo DiCaprio',
  'Djur',
  'Städer i Sverige',
  'Reality-serier',
  'Drinkar',
  'Artister som spelat på Way Out West',
  'Bilmärken',
  'Svenska Youtubers',
  'Sportgrenar',
  'Maträtter från Asien',
  'Netflix-serier',
  'Saker man hittar i en bar',
];

export const CAN_CUP_CARDS: CardBase[] = [
  // ─── COMMON ──────────────────────────────────────────────────────────────
  {
    id: 'cc-take-a-sip',
    name: 'Ta en Klunk',
    description: 'En motståndare tar 1 klunk.',
    manaCost: 0,
    sipCost: 0,
    rarity: CardRarity.COMMON,
    type: 'targeted',
    effect: { type: 'canCupSip', value: 1 },
    requiresTarget: true,
    color: 'cyan',
  },
  {
    id: 'cc-social',
    name: 'Skål!',
    description: 'Alla tar 1 klunk.',
    manaCost: 1,
    sipCost: 1,
    rarity: CardRarity.COMMON,
    type: 'aoe',
    effect: { type: 'canCupAoESip', value: 1 },
    requiresTarget: false,
    color: 'cyan',
  },
  {
    id: 'cc-water-break',
    name: 'Vattenpaus',
    description: 'Få 2 vattensklunkar.',
    manaCost: 0,
    sipCost: 0,
    rarity: CardRarity.COMMON,
    type: 'normal',
    effect: { type: 'canCupWater', value: 2 },
    requiresTarget: false,
    color: 'teal',
  },
  {
    id: 'cc-sip-deflection',
    name: 'Avvisning',
    description: 'Blockera nästa tvingade klunk.',
    manaCost: 0,
    sipCost: 0,
    rarity: CardRarity.COMMON,
    type: 'normal',
    effect: { type: 'canCupDeflect', value: 1 },
    requiresTarget: false,
    color: 'teal',
  },
  {
    id: 'cc-top-up',
    name: 'Fyll på',
    description: 'Lägg tillbaka 2 klunkar i din burk.',
    manaCost: 0,
    sipCost: 0,
    rarity: CardRarity.COMMON,
    type: 'normal',
    effect: { type: 'canCupTopUp', value: 2 },
    requiresTarget: false,
    color: 'blue',
  },

  // ─── RARE ─────────────────────────────────────────────────────────────────
  {
    id: 'cc-double-trouble',
    name: 'Dubbel Trouble',
    description: 'Motståndaren tar 4 klunkar.',
    manaCost: 2,
    sipCost: 2,
    rarity: CardRarity.RARE,
    type: 'targeted',
    effect: { type: 'canCupDoubleTrouble', value: 4 },
    requiresTarget: true,
    color: 'indigo',
  },
  {
    id: 'cc-bottoms-up-prep',
    name: 'Nästan Klar',
    description: 'Motståndaren tvingas ner till 1 klunk kvar.',
    manaCost: 3,
    sipCost: 3,
    rarity: CardRarity.RARE,
    type: 'targeted',
    effect: { type: 'canCupBottomsUpPrep', value: 1 },
    requiresTarget: true,
    color: 'indigo',
  },
  {
    id: 'cc-can-swap',
    name: 'Burkbyte',
    description: 'Byt burk med en motståndare (inte på riktigt...).',
    manaCost: 2,
    sipCost: 2,
    rarity: CardRarity.RARE,
    type: 'targeted',
    effect: { type: 'canCupSwap', value: 0 },
    requiresTarget: true,
    color: 'violet',
  },
  {
    id: 'cc-pressure-wave',
    name: 'Tryckvåg',
    description: 'Motståndaren tar 3 klunkar.',
    manaCost: 1,
    sipCost: 1,
    rarity: CardRarity.RARE,
    type: 'targeted',
    effect: { type: 'canCupSip', value: 3 },
    requiresTarget: true,
    color: 'violet',
  },
  {
    id: 'cc-vampiric-chug',
    name: 'Gimmi Gimmi',
    description: 'Stjäl 2 klunkar från motståndaren.',
    manaCost: 1,
    sipCost: 0,
    rarity: CardRarity.RARE,
    type: 'targeted',
    effect: { type: 'canCupVampire', value: 2 },
    requiresTarget: true,
    color: 'emerald',
  },

  // ─── EPIC ─────────────────────────────────────────────────────────────────
  {
    id: 'cc-arm-wrestle',
    name: 'Armbrytning',
    description: 'Utmana någon — förloraren tar 5 klunkar.',
    manaCost: 3,
    sipCost: 3,
    rarity: CardRarity.EPIC,
    type: 'challenge',
    effect: {
      type: 'challenge',
      value: 0,
      winnerEffect: { type: 'null', value: 0 },
      loserEffect: { type: 'canCupSip', value: 5 },
    },
    requiresTarget: true,
    isChallenge: true,
    color: 'purple',
  },
  {
    id: 'cc-category-random',
    name: 'Kategori',
    description: 'Nämn saker inom kategorin. Den som missar tar 3 klunkar.',
    manaCost: 3,
    sipCost: 3,
    rarity: CardRarity.EPIC,
    type: 'challenge',
    effect: {
      type: 'challenge',
      value: 0,
      winnerEffect: { type: 'null', value: 0 },
      loserEffect: { type: 'canCupSip', value: 3 },
    },
    requiresTarget: true,
    isChallenge: true,
    color: 'purple',
  },
  {
    id: 'cc-the-chug',
    name: 'BOTTEN UPP',
    description: 'Motståndaren måste supa klart sin burk!',
    manaCost: 3,
    sipCost: 3,
    rarity: CardRarity.EPIC,
    type: 'targeted',
    effect: { type: 'canCupBottenUpp', value: 0 },
    requiresTarget: true,
    color: 'rose',
  },

  // ─── LEGENDARY ────────────────────────────────────────────────────────────
  {
    id: 'cc-hur-full-e-du',
    name: 'HUR FULL E DU?',
    description: 'Snabbast hand vinner — förloraren botten-uppar 2 hela burkar.',
    manaCost: 3,
    sipCost: 3,
    rarity: CardRarity.LEGENDARY,
    type: 'challenge',
    effect: {
      type: 'challenge',
      value: 0,
      winnerEffect: { type: 'null', value: 0 },
      loserEffect: { type: 'canCupSip', value: 20 },
    },
    requiresTarget: true,
    isChallenge: true,
    isLegendary: true,
    color: 'amber',
    flavorText: 'Guld är guld. Snabbast hand överlever.',
  },
];
