import { CardBase, CardRarity } from '../../../types/cards';

export const CAN_CUP_CATEGORIES = [
  'Ölmärken',
  'Skidorter',
  'Länder i Europa',
  'Fotbollslag',
  'Filmer med Leonardo DiCaprio',
  'Djur',
  'Städer i Sverige',
  'Reality-serier',
  'Drinkar',
  'Artister som spelat på Way Out West',
  'Bilmärken',
  'Svenska Youtubers',
  'Sportgrenar',
  'Maträtter från Asien',
  'Netflix-serier',
  'Saker man hittar i en bar',
];

export const CAN_CUP_TONGUE_TWISTERS = [
  'Sex laxar i en laxask.',
  'Sju sjösjuka sjömän sköttes av sju sköna sjuksköterskor.',
  'Flyg fula fluga, flyg! Och den fula flugan flög.',
  'Packa pappas kappsäck.',
  'Kvist friskt, raska kvastar.',
  'Knut satt vid en knut och knöt en knut, när Knut hade knutit knuten var knuten knuten.',
  'Droskkusken Max kuskar med raska droskhästar.',
  'En barfotad arab badar i en bäck.',
  'Sex snabba snigel-snappande snokar snodde snopet snoken snabbt.',
  'Sjuttiosju sköna sjuksköterskor sköter sju sjösjuka sjömän på skeppet Shanghai.',
];

export const CAN_CUP_CARDS: CardBase[] = [
  // ─── COMMON ──────────────────────────────────────────────────────────────
  {
    id: 'cc-take-a-sip',
    name: 'Ta en Klunk',
    description: 'En motståndare tar 1 klunk.',
    manaCost: 0,
    sipCost: 0,
    rarity: CardRarity.COMMON,
    type: 'targeted',
    effect: { type: 'canCupSip', value: 1 },
    requiresTarget: true,
    color: 'cyan',
  },
  {
    id: 'cc-social',
    name: 'Skål!',
    description: 'Alla ANDRA tar 2 klunkar.',
    manaCost: 2,
    sipCost: 2,
    rarity: CardRarity.COMMON,
    type: 'aoe',
    effect: { type: 'canCupAoESip', value: 2 },
    requiresTarget: false,
    color: 'cyan',
  },
  {
    id: 'cc-water-break',
    name: 'Vattenpaus',
    description: 'Få 2 vattensklunkar.',
    manaCost: 0,
    sipCost: 0,
    rarity: CardRarity.COMMON,
    type: 'normal',
    effect: { type: 'canCupWater', value: 2 },
    requiresTarget: false,
    color: 'teal',
  },
  {
    id: 'cc-sip-deflection',
    name: 'Block',
    description: 'Blockera nästa tvingade klunk.',
    manaCost: 0,
    sipCost: 0,
    rarity: CardRarity.COMMON,
    type: 'normal',
    effect: { type: 'canCupDeflect', value: 1 },
    requiresTarget: false,
    color: 'teal',
  },
  {
    id: 'cc-top-up',
    name: 'Fyll på',
    description: 'Lägg tillbaka 2 klunkar i din burk.',
    manaCost: 0,
    sipCost: 0,
    rarity: CardRarity.COMMON,
    type: 'normal',
    effect: { type: 'canCupTopUp', value: 2 },
    requiresTarget: false,
    color: 'blue',
  },

  // ─── RARE ─────────────────────────────────────────────────────────────────
  {
    id: 'cc-double-trouble',
    name: 'Dubbel Trouble',
    description: 'Motståndaren tar 4 klunkar.',
    manaCost: 2,
    sipCost: 2,
    rarity: CardRarity.RARE,
    type: 'targeted',
    effect: { type: 'canCupDoubleTrouble', value: 4 },
    requiresTarget: true,
    color: 'indigo',
  },
  {
    id: 'cc-bottoms-up-prep',
    name: 'Nästan Klar',
    description: 'Motståndaren tvingas ner till 1 klunk kvar.',
    manaCost: 3,
    sipCost: 3,
    rarity: CardRarity.RARE,
    type: 'targeted',
    effect: { type: 'canCupBottomsUpPrep', value: 1 },
    requiresTarget: true,
    color: 'indigo',
  },
  {
    id: 'cc-can-swap',
    name: 'Burkbyte',
    description: 'Byt burk med en motståndare (inte på riktigt...).',
    manaCost: 2,
    sipCost: 2,
    rarity: CardRarity.RARE,
    type: 'targeted',
    effect: { type: 'canCupSwap', value: 0 },
    requiresTarget: true,
    color: 'violet',
  },
  {
    id: 'cc-pressure-wave',
    name: 'Tryckvåg',
    description: 'Motståndaren tar 3 klunkar.',
    manaCost: 1,
    sipCost: 1,
    rarity: CardRarity.RARE,
    type: 'targeted',
    effect: { type: 'canCupSip', value: 3 },
    requiresTarget: true,
    color: 'violet',
  },
  {
    id: 'cc-vampiric-chug',
    name: 'Gimmi Gimmi',
    description: 'Stjäl 2 klunkar från motståndaren.',
    manaCost: 1,
    sipCost: 0,
    rarity: CardRarity.RARE,
    type: 'targeted',
    effect: { type: 'canCupVampire', value: 2 },
    requiresTarget: true,
    color: 'emerald',
  },
  {
    id: 'cc-spill',
    name: 'Vaska För I Helvete!',
    description: 'Bort med alla vattensklunkar och blockeringar från målet! De får även 1 straffklunk.',
    manaCost: 2,
    sipCost: 2,
    rarity: CardRarity.RARE, // Can be Epic depending on balance
    type: 'targeted',
    effect: { type: 'canCupRemoveDefense', value: 1 }, // value 1 represents the penalty sip
    requiresTarget: true,
    color: 'red',
  },
  {
    id: 'cc-evaporation',
    name: 'Ökentorka',
    description: 'Alla spelares vattensklunkar förångas direkt. Ingen är säker.',
    manaCost: 3,
    sipCost: 3,
    rarity: CardRarity.RARE,
    type: 'aoe',
    effect: { type: 'canCupRemoveDefense', value: 0 },
    requiresTarget: false,
    color: 'orange',
  },

  // ─── EPIC ─────────────────────────────────────────────────────────────────
  {
    id: 'cc-arm-wrestle',
    name: 'Armbrytning',
    description: 'Utmana någon — förloraren tar 5 klunkar.',
    manaCost: 3,
    sipCost: 3,
    rarity: CardRarity.EPIC,
    type: 'challenge',
    effect: {
      type: 'challenge',
      value: 0,
      winnerEffect: { type: 'null', value: 0 },
      loserEffect: { type: 'canCupSip', value: 5 },
    },
    requiresTarget: true,
    isChallenge: true,
    color: 'purple',
  },
  {
    id: 'cc-category-random',
    name: 'Kategori',
    description: 'Nämn saker inom kategorin. Den som missar tar 3 klunkar.',
    manaCost: 3,
    sipCost: 3,
    rarity: CardRarity.EPIC,
    type: 'challenge',
    effect: {
      type: 'challenge',
      value: 0,
      winnerEffect: { type: 'null', value: 0 },
      loserEffect: { type: 'canCupSip', value: 3 },
    },
    requiresTarget: true,
    isChallenge: true,
    color: 'purple',
  },
  {
    id: 'cc-the-chug',
    name: 'Svep!',
    description: 'Motståndaren måste supa klart sin burk!',
    manaCost: 3,
    sipCost: 3,
    rarity: CardRarity.EPIC,
    type: 'targeted',
    effect: { type: 'canCupBottenUpp', value: 0 },
    requiresTarget: true,
    color: 'rose',
  },
  {
    id: 'cc-tax-the-sober',
    name: 'Skatt På Nykterhet',
    description: 'Den med minst tomma burkar får ta 5 klunkar. (Vid lika lottas det mellan dem)',
    manaCost: 4,
    sipCost: 4,
    rarity: CardRarity.EPIC,
    type: 'auto-targeted', // Custom engine logic or UI
    effect: { type: 'canCupTaxSober', value: 5 },
    requiresTarget: false, // Automatically picks the target logic wise
    color: 'fuchsia',
  },
  {
    id: 'cc-flamingo',
    name: 'Flamingon',
    description: 'Alla ställer sig på ett ben. Den som spelade kortet är domare. Första som tappar balansen tar 5 klunkar.',
    manaCost: 3,
    sipCost: 3,
    rarity: CardRarity.EPIC,
    type: 'challenge',
    effect: {
      type: 'challenge',
      value: 0,
      winnerEffect: { type: 'null', value: 0 },
      loserEffect: { type: 'canCupSip', value: 5 },
    },
    requiresTarget: false, // Everyone but caster
    isChallenge: true,
    color: 'purple',
  },
  {
    id: 'cc-clash-royale-mega-draft',
    name: 'Clash Royale Mega Draft',
    description: 'Välj två duellanter. De öppnar Clash Royale och kör en Classic Mega Draft-duell. När matchen är klar väljer ni vinnare här. Förloraren tar 6 klunkar.',
    manaCost: 3,
    sipCost: 3,
    rarity: CardRarity.EPIC,
    type: 'challenge',
    effect: {
      type: 'challenge',
      value: 0,
      winnerEffect: { type: 'null', value: 0 },
      loserEffect: { type: 'canCupSip', value: 6 },
    },
    requiresTarget: true,
    isChallenge: true,
    color: 'purple',
  },
  {
    id: 'cc-tongue-twister',
    name: 'Tungvrickaren',
    description: 'Välj ett offer. De måste läsa en sjukt svår tungvrickare felfritt. Stakar de sig tar de 3 klunkar.',
    manaCost: 2,
    sipCost: 2,
    rarity: CardRarity.EPIC,
    type: 'challenge',
    effect: {
      type: 'challenge',
      value: 0,
      winnerEffect: { type: 'null', value: 0 },
      loserEffect: { type: 'canCupSip', value: 3 },
    },
    requiresTarget: true,
    isChallenge: true,
    color: 'purple',
  },

  // ─── LEGENDARY ────────────────────────────────────────────────────────────
  {
    id: 'cc-hur-full-e-du',
    name: 'HUR FULL E DU?',
    description: 'Snabbast hand vinner — förloraren botten-uppar 2 hela burkar.',
    manaCost: 3,
    sipCost: 3,
    rarity: CardRarity.LEGENDARY,
    type: 'challenge',
    effect: {
      type: 'challenge',
      value: 0,
      winnerEffect: { type: 'null', value: 0 },
      loserEffect: { type: 'canCupSip', value: 20 },
    },
    requiresTarget: true,
    isChallenge: true,
    isLegendary: true,
    color: 'amber',
    flavorText: 'Guld är guld. Snabbast hand överlever.',
  },
  {
    id: 'cc-bottom-race-random',
    name: 'BOTTENRACE',
    description: 'Du får en slumpad motståndare. Ni racear till botten av burken ni har just nu. Bordet avgör vinnaren. Vinnaren får 10 shields.',
    manaCost: 5,
    sipCost: 5,
    rarity: CardRarity.LEGENDARY,
    type: 'challenge',
    effect: {
      type: 'challenge',
      value: 0,
      winnerEffect: { type: 'canCupDeflect', value: 10 },
      loserEffect: { type: 'null', value: 0 },
    },
    requiresTarget: false,
    isChallenge: true,
    isLegendary: true,
    color: 'amber',
    flavorText: 'Hoppas din burk inte redan är tom...',
  },
  {
    id: 'cc-give-empty-can',
    name: 'PANTA MIN BURK!',
    description: 'Ge bort en av dina tomma burkar till en stackare. *Varning: Mycket trasig mekanik, förvänta dig bråk.*',
    manaCost: 5,
    sipCost: 5,
    rarity: CardRarity.LEGENDARY,
    type: 'targeted',
    effect: { type: 'canCupGiveEmptyCan', value: 1 },
    requiresTarget: true,
    isLegendary: true,
    color: 'amber',
    flavorText: 'Pantamera!',
  },
];
